name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.25.1
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Go env
        run: go env

      - name: Download deps
        run: go mod download

      # Build Web UI assets so //go:embed all:dist matches files in ui/ and server embed
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Enable corepack
        run: corepack enable

      - name: Install UI deps
        working-directory: ui
        run: pnpm install --frozen-lockfile

      - name: Build UI (Vite)
        working-directory: ui
        run: pnpm run build

      - name: Sync built UI into server embed
        run: |
          rm -rf internal/webui/embed/dist
          mkdir -p internal/webui/embed
          cp -R ui/dist internal/webui/embed/dist

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage.out
